name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧
        run: |
          npm install
          # Como o build padrão faz o build completo incluindo o server.ts,
          # para o GitHub Pages (que é apenas estático) nós rodamos apenas o vite build
          npx vite build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # A pasta onde o Vite gera o build estático
          branch: gh-pages # A branch de destino para o GitHub Pages
